package mylang.gui;

/*
 * DialogPreferences.java
 *
 * Created on 21 listopad 2003, 19:55
 *
 * Copyright 2003 Michal Dabrowski
 *
 * This file is part of MyLang.
 *
 * MyLang is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * MyLang is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MyLang; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 *
 * @author  herrmic
 */
public class DialogPreferences extends javax.swing.JDialog
{
	
	/** Creates new form DialogPreferences */
	public DialogPreferences(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
		
		m_checkboxRequireAllTranslations.setSelected(
		MyLang.getPrefRequireAllTranslations());
		m_checkboxEmphasizeMistakes.setSelected(
		MyLang.getPrefEmphasizeMistakes());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		jPanel1 = new javax.swing.JPanel();
		m_checkboxRequireAllTranslations = new javax.swing.JCheckBox();
		m_checkboxEmphasizeMistakes = new javax.swing.JCheckBox();
		jSeparator1 = new javax.swing.JSeparator();
		m_buttonOk = new javax.swing.JButton();
		m_buttonCancel = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		
		getContentPane().setLayout(new java.awt.GridBagLayout());
		
		setTitle("Preferences");
		setModal(true);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				closeDialog(evt);
			}
		});
		
		jPanel1.setLayout(new java.awt.GridBagLayout());
		
		m_checkboxRequireAllTranslations.setText("Require ALL translations");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(m_checkboxRequireAllTranslations, gridBagConstraints);
		
		m_checkboxEmphasizeMistakes.setText("Display message box on every wrong answer");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(m_checkboxEmphasizeMistakes, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		getContentPane().add(jPanel1, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jSeparator1, gridBagConstraints);
		
		m_buttonOk.setText("OK");
		m_buttonOk.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_buttonOkActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(m_buttonOk, gridBagConstraints);
		
		m_buttonCancel.setText("Cancel");
		m_buttonCancel.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_buttonCancelActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(m_buttonCancel, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		gridBagConstraints.weightx = 1.0;
		getContentPane().add(jPanel2, gridBagConstraints);
		
		pack();
	}//GEN-END:initComponents

	private void m_buttonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_buttonOkActionPerformed
	{//GEN-HEADEREND:event_m_buttonOkActionPerformed
		MyLang.setPrefRequireAllTranslations( 
		m_checkboxRequireAllTranslations.getSelectedObjects() != null);
		MyLang.setPrefEmphasizeMistakes( 
		m_checkboxEmphasizeMistakes.getSelectedObjects() != null);
		close();
	}//GEN-LAST:event_m_buttonOkActionPerformed

	private void m_buttonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_buttonCancelActionPerformed
	{//GEN-HEADEREND:event_m_buttonCancelActionPerformed
		close();
	}//GEN-LAST:event_m_buttonCancelActionPerformed
	
	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
	{
		close();
	}//GEN-LAST:event_closeDialog
		
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JButton m_buttonCancel;
	private javax.swing.JButton m_buttonOk;
	private javax.swing.JCheckBox m_checkboxEmphasizeMistakes;
	private javax.swing.JCheckBox m_checkboxRequireAllTranslations;
	// End of variables declaration//GEN-END:variables
	
	private void close()
	{
		setVisible(false);
		dispose();
	}
}
