package mylang.gui;

import mylang.MyLang;
import mylang.data.*;
import java.awt.event.*;
import java.text.*;
import java.util.*;
import javax.swing.*;

/*
 * DialogSession.java
 *
 * Created on 4 listopad 2003, 19:20
 *
 * Copyright 2003 Michal Dabrowski
 *
 * This file is part of MyLang.
 *
 * MyLang is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * MyLang is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MyLang; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 *
 * @author  herrmic
 */
public class DialogSession extends javax.swing.JDialog
{
	public static final int TEACH_MODE = 1;
	public static final int TEST_MODE = 2;
	
	private int m_mode;
	private int m_languageOfQuestion;
	private int m_languageOfAnswer;
	private DictionarySet m_dset;
	
	private int m_answers;
	private int m_correct;
	private ArrayList m_wordsLeft;
	private ArrayList m_wordsFailed;
	private Word m_question;
	
	private javax.swing.Timer m_timerElapsed;
	private Calendar m_timeElapsed;
	
	private Random m_random;
	
	private final String[] m_correctComments =
	{"CORRECT", "OK", "GOOD"};
	private int m_lastCorrectComment;
	
	/** Creates new form DialogSession */
	public DialogSession(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
		
		m_timerElapsed = new javax.swing.Timer(1000, new ActionListener()
		{
			public void actionPerformed(ActionEvent evt)
			{
				DecimalFormat df = new DecimalFormat("00");
				m_timeElapsed.add(Calendar.SECOND, 1);
				m_textStatTime.setText(
				df.format(m_timeElapsed.get(Calendar.MINUTE)) + ":"
				+ df.format(m_timeElapsed.get(Calendar.SECOND)));
			}
		});
		m_timeElapsed = Calendar.getInstance();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		jLabel1 = new javax.swing.JLabel();
		m_textQuestion = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		m_textAnswer = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		m_textTranslator = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		m_textStatAnswers = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		m_textStatLeft = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		m_textStatCorrect = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		m_textStatTime = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		m_buttonCheck = new javax.swing.JButton();
		m_buttonCancel = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jSeparator1 = new javax.swing.JSeparator();
		
		getContentPane().setLayout(new java.awt.GridBagLayout());
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("MyLang - Session");
		setModal(true);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				closeDialog(evt);
			}
		});
		
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel1.setText("Question");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jLabel1, gridBagConstraints);
		
		m_textQuestion.setEditable(false);
		m_textQuestion.setToolTipText("<HTML>Question is displayed here.<BR>\nThis is the word you are asked to translate.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(m_textQuestion, gridBagConstraints);
		
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel2.setText("Answer");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jLabel2, gridBagConstraints);
		
		m_textAnswer.setToolTipText("<HTML>Type your answer here.<BR>\nHere you type translation of the word displayed in the <B>\"Question\"</B> field.\n</HTML>");
		m_textAnswer.setPreferredSize(new java.awt.Dimension(508, 21));
		m_textAnswer.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_textAnswerActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(m_textAnswer, gridBagConstraints);
		
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel3.setText("Translator");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jLabel3, gridBagConstraints);
		
		m_textTranslator.setEditable(false);
		m_textTranslator.setToolTipText("<HTML>Comment of your last answer.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(m_textTranslator, gridBagConstraints);
		
		jPanel1.setLayout(new java.awt.GridBagLayout());
		
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel4.setText("Session stats:");
		jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(jLabel4, gridBagConstraints);
		
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel5.setText("question:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(jLabel5, gridBagConstraints);
		
		m_textStatAnswers.setEditable(false);
		m_textStatAnswers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		m_textStatAnswers.setText("0");
		m_textStatAnswers.setToolTipText("<HTML>Number of the question.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(m_textStatAnswers, gridBagConstraints);
		
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel6.setText("left:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(jLabel6, gridBagConstraints);
		
		m_textStatLeft.setEditable(false);
		m_textStatLeft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		m_textStatLeft.setToolTipText("<HTML>Number of the words left.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(m_textStatLeft, gridBagConstraints);
		
		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel7.setText("correct:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(jLabel7, gridBagConstraints);
		
		m_textStatCorrect.setEditable(false);
		m_textStatCorrect.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		m_textStatCorrect.setText("0");
		m_textStatCorrect.setToolTipText("<HTML>Number of your correct answers.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(m_textStatCorrect, gridBagConstraints);
		
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel8.setText("time:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(jLabel8, gridBagConstraints);
		
		m_textStatTime.setEditable(false);
		m_textStatTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		m_textStatTime.setText("00:00");
		m_textStatTime.setToolTipText("<HTML>Time that has ellapsed during this session.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(m_textStatTime, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jPanel1, gridBagConstraints);
		
		jPanel2.setLayout(new java.awt.GridBagLayout());
		
		m_buttonCheck.setText("Check");
		m_buttonCheck.setToolTipText("<HTML>Use this button to acknowledge your answer.<BR>\n<I>Note: it is usually better to hit Enter instead.</I>\n</HTML>");
		m_buttonCheck.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_buttonCheckActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(m_buttonCheck, gridBagConstraints);
		
		m_buttonCancel.setText("Cancel");
		m_buttonCancel.setToolTipText("<HTML>Interrupts this session.<BR>\n<I>Note: cancelled session is not counted into the dictioraies stats.</I>\n</HTML>");
		m_buttonCancel.setDefaultCapable(false);
		m_buttonCancel.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_buttonCancelActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(m_buttonCancel, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(jPanel3, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jPanel2, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		getContentPane().add(jSeparator1, gridBagConstraints);
		
		pack();
	}//GEN-END:initComponents
	
	private void m_buttonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_buttonCancelActionPerformed
	{//GEN-HEADEREND:event_m_buttonCancelActionPerformed
		cancelSession();
	}//GEN-LAST:event_m_buttonCancelActionPerformed
	
	private void m_buttonCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_buttonCheckActionPerformed
	{//GEN-HEADEREND:event_m_buttonCheckActionPerformed
		checkAnswer();
	}//GEN-LAST:event_m_buttonCheckActionPerformed
	
	private void m_textAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_textAnswerActionPerformed
	{//GEN-HEADEREND:event_m_textAnswerActionPerformed
		checkAnswer();
	}//GEN-LAST:event_m_textAnswerActionPerformed
	
	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
	{
		cancelSession();
	}//GEN-LAST:event_closeDialog
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JButton m_buttonCancel;
	private javax.swing.JButton m_buttonCheck;
	private javax.swing.JTextField m_textAnswer;
	private javax.swing.JTextField m_textQuestion;
	private javax.swing.JTextField m_textStatAnswers;
	private javax.swing.JTextField m_textStatCorrect;
	private javax.swing.JTextField m_textStatLeft;
	private javax.swing.JTextField m_textStatTime;
	private javax.swing.JTextField m_textTranslator;
	// End of variables declaration//GEN-END:variables
	
	public void prepareSession(int mode, int loq, DictionarySet dset)
	{
		m_mode = mode;
		m_languageOfQuestion = loq;
		if(loq == 0)
			m_languageOfAnswer = 1;
		else
			m_languageOfAnswer = 0;
		m_dset = dset;
		m_wordsLeft = new ArrayList();
		for(Iterator i = m_dset.getWordsList().iterator(); i.hasNext();)
		{
			Word w = (Word)i.next();
			if(w.getEnabled())
				m_wordsLeft.add(w);
		}
		m_wordsFailed = new ArrayList();
		m_timeElapsed.set(Calendar.HOUR, 0);
		m_timeElapsed.set(Calendar.MINUTE, 0);
		m_timeElapsed.set(Calendar.SECOND, 0);
		m_random = new Random();
		m_timerElapsed.restart();
		m_lastCorrectComment = 0;
		askNewQuestion();
	}
	
	private void askNewQuestion()
	{
		m_textAnswer.setText("");
		m_textStatAnswers.setText(String.valueOf(m_answers + 1));
		m_textStatCorrect.setText(String.valueOf(m_correct));
		m_textStatLeft.setText(String.valueOf(m_wordsLeft.size()));
		if(m_wordsLeft.size() == 0)
		{
			finalizeSession();
		}
		else
		{
			int num = m_random.nextInt(m_wordsLeft.size());
			m_question = (Word)m_wordsLeft.get(num);
			m_textQuestion.setText(m_question.getLanguage(m_languageOfQuestion));
			m_textAnswer.requestFocus();
		}
	}
	
	private void checkAnswer()
	{
		String[] userTab = m_textAnswer.getText().trim().split(";");
		String[] answerTab = m_question.getLanguage(m_languageOfAnswer).split(";");
		boolean correct = false;
		if(MyLang.getPrefRequireAllTranslations())
		{
			if(isArraySubsetOf(userTab, answerTab)
			&& isArraySubsetOf(answerTab, userTab))
				correct = true;
		}
		else
		{
			if(isArraySubsetOf(userTab, answerTab))
				correct = true;
		}
		
		if(correct)
		{
			m_lastCorrectComment++;
			if(m_lastCorrectComment >= m_correctComments.length)
				m_lastCorrectComment = 0;
			m_textTranslator.setText(m_correctComments[m_lastCorrectComment]);
			m_wordsLeft.remove(m_question);
			m_correct++;
		}
		else
		{
			m_textTranslator.setText(
			m_question.getLanguage(m_languageOfQuestion) + ": "
			+ m_question.getLanguage(m_languageOfAnswer));
			
			if(MyLang.getPrefEmphasizeMistakes())
				JOptionPane.showMessageDialog(this,
				"<HTML><CENTER>Wrong answer!<BR>The correct translation of:<BR><BR>"
				+ "<B>" + m_question.getLanguage(m_languageOfQuestion) + "</B><BR><BR>"
				+ "is:<BR><BR>"
				+ "<B>" + m_question.getLanguage(m_languageOfAnswer) + "</B"
				+ "</CENTER></HTML>",
				"Message", JOptionPane.INFORMATION_MESSAGE);
			
			if(m_mode == TEST_MODE)
				m_wordsLeft.remove(m_question);
			m_wordsFailed.add(m_question);
		}
		m_answers++;
		askNewQuestion();
	}
	
	private boolean isArraySubsetOf(String[] array, String[] set)
	{
		boolean found;
		for(int i = 0; i < array.length; i++)
		{
			found = false;
			for(int j = 0; j < set.length; j++)
			{
				if(array[i].trim().compareToIgnoreCase(set[j].trim()) == 0)
				{
					found = true;
					break;
				}
			}
			if(!found)
				return false;
		}
		return true;
	}
	
	private void finalizeSession()
	{
		m_timerElapsed.stop();
		m_textQuestion.setText("");
		m_textAnswer.setEnabled(false);
		m_textAnswer.setEditable(false);
		m_textStatAnswers.setText(String.valueOf(m_answers));
		m_buttonCheck.setEnabled(false);
		m_buttonCancel.setText("Close");
		for(Iterator i = m_dset.getWordsList().iterator(); i.hasNext();)
		{
			Word w = (Word)i.next();
			if(w.getEnabled())
				w.setLastStat(new Stat(0));
		}
		for(Iterator i = m_wordsFailed.iterator(); i.hasNext();)
		{
			Word w = (Word)i.next();
			w.setLastStat(new Stat(w.getLastStat().getScore() + 1));
		}
		for(Iterator i = m_dset.getDictionaries().iterator(); i.hasNext();)
		{
			mylang.data.Dictionary dict = (mylang.data.Dictionary)i.next();
			try
			{
				int failures;
				failures = 0;
				for(Iterator j = m_wordsFailed.iterator(); j.hasNext();)
				{
					Word w = (Word)j.next();
					if(dict.getWordsList().contains(w))
						failures++;
				}
				dict.getStats().add(new Stat(failures, new Integer(m_mode), m_timeElapsed));
				dict.write(dict.getFile());
			}
			catch(Exception ex)
			{
				JOptionPane.showMessageDialog(this,
				"Cannot update stats for file \"" + dict.getFile() + "\"\n"
				+ ex.getMessage(),
				"Error", JOptionPane.ERROR_MESSAGE);
			}
		}
	}
	
	private void cancelSession()
	{
		if((m_answers > 0) && (m_wordsLeft.size() > 0))
		{
			if(JOptionPane.showConfirmDialog(this,
			"Do you really want to interrupt this session?",
			"Question", JOptionPane.YES_NO_OPTION,
			JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION)
				return;
		}
		setVisible(false);
		dispose();
	}
}
