package mylang.gui;

import mylang.MyLang;
import mylang.data.*;
import mylang.gui.models.*;
import java.io.*;
import javax.swing.*;
import javax.swing.event.*;

/*
 * FrameEditor.java
 *
 * Created on 10 pa¼dziernik 2003, 20:57
 *
 * Copyright 2003 Michal Dabrowski
 *
 * This file is part of MyLang.
 *
 * MyLang is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * MyLang is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MyLang; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 *
 * @author  herrmic
 */
public class FrameEditor extends javax.swing.JFrame
{
	private boolean m_modified;
	private Dictionary m_dict;
	
	/** Creates new form FrameEditor */
	public FrameEditor()
	{
		initComponents();
		m_tableWords.getModel().addTableModelListener(new TableModelListener()
		{
			public void tableChanged(TableModelEvent evt)
			{
				m_modified = true;
			}
		});
		DocumentListener dl = new DocumentListener()
		{
			public void changedUpdate(DocumentEvent evt)
			{
				m_modified = true;
				updateTableHeaders();
			}
			
			public void insertUpdate(DocumentEvent evt)
			{
				m_modified = true;
				updateTableHeaders();
			}
			
			public void removeUpdate(DocumentEvent evt)
			{
				m_modified = true;
				updateTableHeaders();
			}
		};
		m_textLanguage0.getDocument().addDocumentListener(dl);
		m_textLanguage1.getDocument().addDocumentListener(dl);
		m_textDescription.getDocument().addDocumentListener(dl);
		m_modified = false;
		newFile();
		updateTableHeaders();
		
		setLocationRelativeTo(null);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		m_filechooserDictionary = new javax.swing.JFileChooser();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		m_textLanguage0 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		m_textLanguage1 = new javax.swing.JTextField();
		m_textDescription = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		m_tableWords = new javax.swing.JTable();
		m_buttonAdd = new javax.swing.JButton();
		m_buttonRemove = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		m_labelStatusWords = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu2 = new javax.swing.JMenu();
		m_menuFileNew = new javax.swing.JMenuItem();
		m_menuFileOpen = new javax.swing.JMenuItem();
		m_menuFileSave = new javax.swing.JMenuItem();
		m_menuFileSaveas = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JSeparator();
		m_menuFileClose = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		m_menuEditAdd = new javax.swing.JMenuItem();
		m_menuEditRemove = new javax.swing.JMenuItem();
		
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("MyLang - Editor");
		setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("resources/logo16x16.png")));
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				formWindowClosing(evt);
			}
		});
		
		jPanel2.setLayout(new java.awt.GridBagLayout());
		
		jLabel1.setDisplayedMnemonic('L');
		jLabel1.setLabelFor(m_textLanguage0);
		jLabel1.setText("Languages");
		jLabel1.setFocusable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(jLabel1, gridBagConstraints);
		
		m_textLanguage0.setToolTipText("<HTML>Name of the first language of the dictionary.</HTML>");
		m_textLanguage0.setFocusAccelerator('L');
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(m_textLanguage0, gridBagConstraints);
		
		jLabel3.setDisplayedMnemonic('D');
		jLabel3.setLabelFor(m_textDescription);
		jLabel3.setText("Description");
		jLabel3.setFocusable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(jLabel3, gridBagConstraints);
		
		m_textLanguage1.setToolTipText("<HTML>Name of the second language of the dictionary.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(m_textLanguage1, gridBagConstraints);
		
		m_textDescription.setToolTipText("<HTML>Short description of the dictionary.</HTML>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(m_textDescription, gridBagConstraints);
		
		jLabel4.setDisplayedMnemonic('W');
		jLabel4.setLabelFor(m_tableWords);
		jLabel4.setText("Words");
		jLabel4.setFocusable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(jLabel4, gridBagConstraints);
		
		jPanel1.setLayout(new java.awt.GridBagLayout());
		
		jScrollPane1.setToolTipText("<HTML>Table of all words contained in the dictionary.</HTML>");
		m_tableWords.setModel(new WordsEditorTableModel());
		jScrollPane1.setViewportView(m_tableWords);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridheight = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(jScrollPane1, gridBagConstraints);
		
		m_buttonAdd.setMnemonic('A');
		m_buttonAdd.setText("Add");
		m_buttonAdd.setToolTipText("<HTML>Adds new word to the table.</HTML>");
		m_buttonAdd.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_buttonAddActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(m_buttonAdd, gridBagConstraints);
		
		m_buttonRemove.setMnemonic('R');
		m_buttonRemove.setText("Remove");
		m_buttonRemove.setToolTipText("<HTML>Removes all selected words from the table.</HTML>");
		m_buttonRemove.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_buttonRemoveActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel1.add(m_buttonRemove, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel2.add(jPanel1, gridBagConstraints);
		
		getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
		
		jPanel3.setLayout(new java.awt.GridBagLayout());
		
		m_labelStatusWords.setText("Words: 0");
		m_labelStatusWords.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("controlShadow")));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.ipadx = 2;
		gridBagConstraints.ipady = 2;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 1);
		jPanel3.add(m_labelStatusWords, gridBagConstraints);
		
		jPanel4.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("controlShadow")), new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1))));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 2);
		gridBagConstraints.weightx = 1.0;
		jPanel3.add(jPanel4, gridBagConstraints);
		
		getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);
		
		jMenu2.setMnemonic('F');
		jMenu2.setText("File");
		m_menuFileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
		m_menuFileNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylang/gui/resources/New16.gif")));
		m_menuFileNew.setText("New");
		m_menuFileNew.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuFileNewActionPerformed(evt);
			}
		});
		
		jMenu2.add(m_menuFileNew);
		
		m_menuFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
		m_menuFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylang/gui/resources/Open16.gif")));
		m_menuFileOpen.setText("Open...");
		m_menuFileOpen.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuFileOpenActionPerformed(evt);
			}
		});
		
		jMenu2.add(m_menuFileOpen);
		
		m_menuFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
		m_menuFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylang/gui/resources/Save16.gif")));
		m_menuFileSave.setText("Save");
		m_menuFileSave.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuFileSaveActionPerformed(evt);
			}
		});
		
		jMenu2.add(m_menuFileSave);
		
		m_menuFileSaveas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylang/gui/resources/SaveAs16.gif")));
		m_menuFileSaveas.setText("Save as...");
		m_menuFileSaveas.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuFileSaveasActionPerformed(evt);
			}
		});
		
		jMenu2.add(m_menuFileSaveas);
		
		jMenu2.add(jSeparator1);
		
		m_menuFileClose.setText("Close");
		m_menuFileClose.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuFileCloseActionPerformed(evt);
			}
		});
		
		jMenu2.add(m_menuFileClose);
		
		jMenuBar2.add(jMenu2);
		
		jMenu1.setMnemonic('E');
		jMenu1.setText("Edit");
		m_menuEditAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
		m_menuEditAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylang/gui/resources/RowInsertAfter16.gif")));
		m_menuEditAdd.setText("Add");
		m_menuEditAdd.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuEditAddActionPerformed(evt);
			}
		});
		
		jMenu1.add(m_menuEditAdd);
		
		m_menuEditRemove.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.ALT_MASK));
		m_menuEditRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylang/gui/resources/RowDelete16.gif")));
		m_menuEditRemove.setText("Remove");
		m_menuEditRemove.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				m_menuEditRemoveActionPerformed(evt);
			}
		});
		
		jMenu1.add(m_menuEditRemove);
		
		jMenuBar2.add(jMenu1);
		
		setJMenuBar(jMenuBar2);
		
		pack();
	}//GEN-END:initComponents
				
	private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
	{//GEN-HEADEREND:event_formWindowClosing
		if(canFileBeClosed())
			dispose();
	}//GEN-LAST:event_formWindowClosing
	
	private void m_menuFileCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuFileCloseActionPerformed
	{//GEN-HEADEREND:event_m_menuFileCloseActionPerformed
		if(canFileBeClosed())
			dispose();
	}//GEN-LAST:event_m_menuFileCloseActionPerformed
	
	private void m_menuFileSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuFileSaveActionPerformed
	{//GEN-HEADEREND:event_m_menuFileSaveActionPerformed
		saveFile(m_dict.getFile());
	}//GEN-LAST:event_m_menuFileSaveActionPerformed
	
	private void m_menuFileNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuFileNewActionPerformed
	{//GEN-HEADEREND:event_m_menuFileNewActionPerformed
		newFile();
	}//GEN-LAST:event_m_menuFileNewActionPerformed
	
	private void m_menuEditRemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuEditRemoveActionPerformed
	{//GEN-HEADEREND:event_m_menuEditRemoveActionPerformed
		removeSelectedWords();
	}//GEN-LAST:event_m_menuEditRemoveActionPerformed
	
	private void m_buttonRemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_buttonRemoveActionPerformed
	{//GEN-HEADEREND:event_m_buttonRemoveActionPerformed
		removeSelectedWords();
	}//GEN-LAST:event_m_buttonRemoveActionPerformed
	
	private void m_menuEditAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuEditAddActionPerformed
	{//GEN-HEADEREND:event_m_menuEditAddActionPerformed
		insertNewWord();
	}//GEN-LAST:event_m_menuEditAddActionPerformed
	
	private void m_buttonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_buttonAddActionPerformed
	{//GEN-HEADEREND:event_m_buttonAddActionPerformed
		insertNewWord();
	}//GEN-LAST:event_m_buttonAddActionPerformed
	
	private void m_menuFileSaveasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuFileSaveasActionPerformed
	{//GEN-HEADEREND:event_m_menuFileSaveasActionPerformed
		saveFile(null);
	}//GEN-LAST:event_m_menuFileSaveasActionPerformed
	
	private void m_menuFileOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_menuFileOpenActionPerformed
	{//GEN-HEADEREND:event_m_menuFileOpenActionPerformed
		loadFile();
	}//GEN-LAST:event_m_menuFileOpenActionPerformed
	
	/** Exit the Application */
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JButton m_buttonAdd;
	private javax.swing.JButton m_buttonRemove;
	private javax.swing.JFileChooser m_filechooserDictionary;
	private javax.swing.JLabel m_labelStatusWords;
	private javax.swing.JMenuItem m_menuEditAdd;
	private javax.swing.JMenuItem m_menuEditRemove;
	private javax.swing.JMenuItem m_menuFileClose;
	private javax.swing.JMenuItem m_menuFileNew;
	private javax.swing.JMenuItem m_menuFileOpen;
	private javax.swing.JMenuItem m_menuFileSave;
	private javax.swing.JMenuItem m_menuFileSaveas;
	private javax.swing.JTable m_tableWords;
	private javax.swing.JTextField m_textDescription;
	private javax.swing.JTextField m_textLanguage0;
	private javax.swing.JTextField m_textLanguage1;
	// End of variables declaration//GEN-END:variables
	
	private void loadFile()
	{
		// Make sure, that we won't close file accidentally
		if(canFileBeClosed())
		{
			// Get the latest used path for the file dialog
			m_filechooserDictionary.setCurrentDirectory(
			new File(MyLang.getPrefDictionariesPath()));
			if(m_filechooserDictionary.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
			{
				// Store the path for later use
				MyLang.setPrefDictionariesPath(m_filechooserDictionary
				.getSelectedFile().getAbsolutePath());
				
				try
				{
					// Load the selected dictionary then fill the controls
					// with data
					m_dict = new Dictionary(m_filechooserDictionary.getSelectedFile());
					m_textLanguage0.setText(m_dict.getLanguageNames()[0]);
					m_textLanguage1.setText(m_dict.getLanguageNames()[1]);
					m_textDescription.setText(m_dict.getDescription());
					((WordsEditorTableModel)m_tableWords.getModel()).setDictionary(m_dict);
					updateTitle();
					updateStatusBar();
					
					// Set that the file is freshly loaded
					m_modified = false;
				}
				catch(IOException ex)
				{
					JOptionPane.showMessageDialog(this, ex.getMessage(),
					"Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
	}
	
	private void saveFile(File f)
	{
		// Ensure that entered data is correct
		if(canFileBeSaved())
		{
			// Make new variable, to avoid changing the param
			File file = f;
			
			// If the file passed as a param is null, then need to ask user
			// for the file name.
			if(file == null)
			{
				// Get the latest used path for the file dialog
				m_filechooserDictionary.setCurrentDirectory(
				new File(MyLang.getPrefDictionariesPath()));				
				if(m_filechooserDictionary.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
				{
					// Store the path for later use
					MyLang.setPrefDictionariesPath(m_filechooserDictionary
					.getSelectedFile().getAbsolutePath());

					// Remember the selected file
					file = m_filechooserDictionary.getSelectedFile();
					
					// Check, if the file already exists and display
					// warning is necessary
					if(file.exists())
					{
						if(JOptionPane.showConfirmDialog(this,
						"The file already exists. Overwrite it?",
						"Question", JOptionPane.YES_NO_OPTION,
						JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION)
						{
							file = null;
						}
					}
				}
			}
			
			// If the file is still null, it means user did not selected one
			if(file != null)
			{
				try
				{
					m_dict.getLanguageNames()[0] = m_textLanguage0.getText();
					m_dict.getLanguageNames()[1] = m_textLanguage1.getText();
					m_dict.setDescription(m_textDescription.getText());
					m_dict.write(file);
					m_modified = false;
					updateTitle();
				}
				catch(IOException ex)
				{
					JOptionPane.showMessageDialog(this, ex.getMessage(),
					"Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
	}
	
	private void newFile()
	{
		// Make sure, that we won't close file accidentally
		if(canFileBeClosed())
		{
			// Clean everything
			m_dict = new Dictionary();
			m_textLanguage0.setText("");
			m_textLanguage1.setText("");
			m_textDescription.setText("");
			((WordsEditorTableModel)m_tableWords.getModel()).setDictionary(m_dict);
			m_modified = false;
			updateTitle();
			updateStatusBar();
		}
	}
	
	/** Ensures it is safe to close the file (to prevent accidental data loss).
	 * Asks the user if necessary.
	*/
	private boolean canFileBeClosed()
	{
		if(m_modified)
		{
			if(JOptionPane.showConfirmDialog(this,
			"File has been modified - all changes will be lost. Do you want to continue?",
			"Warning", JOptionPane.YES_NO_OPTION,
			JOptionPane.WARNING_MESSAGE) == JOptionPane.NO_OPTION)
			{
				return false;
			}
		}
		return true;
	}
	
	/** Updated words table headers according to the language names */
	private void updateTableHeaders()
	{
		String s;
		
		s = m_textLanguage0.getText();
		if(s.compareTo("") == 0)
			s = "Language 1";
		m_tableWords.getColumnModel().getColumn(
		m_tableWords.convertColumnIndexToView(0)).setHeaderValue(s);
		
		s = m_textLanguage1.getText();
		if(s.compareTo("") == 0)
			s = "Language 2";
		m_tableWords.getColumnModel().getColumn(
		m_tableWords.convertColumnIndexToView(1)).setHeaderValue(s);
		
		m_tableWords.getTableHeader().resizeAndRepaint();
	}
	
	/** Evaluates if the languages are entered properly.
	 * Displays message box if there is something wrong.
	*/
	private boolean canFileBeSaved()
	{
		// Check if both language names are provided
		if(m_textLanguage0.getText().compareTo("") == 0 ||
			m_textLanguage1.getText().compareTo("") == 0)
		{
			JOptionPane.showMessageDialog(this,
				"Language name may not be empty",
				"Information", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		
		// Check if language names are not equal
		if(m_textLanguage0.getText().trim().compareToIgnoreCase(
			m_textLanguage1.getText().trim()) == 0)
		{
			JOptionPane.showMessageDialog(this,
				"Language names must not be same",
				"Information", JOptionPane.INFORMATION_MESSAGE);
			return false;
		}
		
		// No errors occured - file can be saved
		return true;
	}
	
	/** Sets the frame's title depending on file name */
	private void updateTitle()
	{
		// Set the appropriate window title
		if(m_dict.getFile() != null)
		{
			setTitle("MyLang - " + m_dict.getFile().getName() + " - Editor");
		}
		else
		{
			setTitle("MyLang - Editor");
		}
	}
	
	private void removeSelectedWords()
	{
		((WordsEditorTableModel)m_tableWords.getModel()).removeWords(m_tableWords.getSelectedRows());
		updateStatusBar();
	}
	
	private void insertNewWord()
	{
		((WordsEditorTableModel)m_tableWords.getModel()).addWord();
		updateStatusBar();
	}
	
	private void updateStatusBar()
	{
		m_labelStatusWords.setText("Words: " + m_tableWords.getRowCount());
	}
}
